export const ghostwriter = {
    "1": ["GeminiAPI", "Determine the most suitable genre and target audience for a story based on the following concept: {initialPrompt}"],
    "2": ["MobleysoftMASCOM", "Process genre and target audience data: {previousOutput}"],
    "3": ["GeminiAPI", "Synthesize a comprehensive world-building bible from the provided inputs: {initialPrompt} {uploadedImages} {genre} {targetAudience}"],
    "4": ["MobleysoftMASCOM", "Process world-building bible: {previousOutput}"],
    "5": ["GeminiAPI", "Analyze and refine the world-building bible: {previousOutput}"],
    "6": ["MobleysoftMASCOM", "Process refined world-building bible: {previousOutput}"],
    "7": ["GeminiAPI", "Develop a cast of compelling characters: {previousOutput}"],
    "8": ["MobleysoftMASCOM", "Process character details: {previousOutput}"],
    "9": ["GeminiAPI", "Create detailed backstories, motivations, and relationships for each character: {previousOutput}"],
    "10": ["MobleysoftMASCOM", "Process character backstories: {previousOutput}"],
    "11": ["GeminiAPI", "Expand on the settings described in the world-building bible: {previousOutput}"],
    "12": ["MobleysoftMASCOM", "Process expanded settings: {previousOutput}"],
    "13": ["GeminiAPI", "Consider cultural nuances, historical significance, and potential conflicts associated with each setting: {previousOutput}"],
    "14": ["MobleysoftMASCOM", "Process enhanced settings: {previousOutput}"],
    "15": ["GeminiAPI", "Brainstorm and create a detailed outline for a 16-chapter novel: {previousOutput}"],
    "16": ["MobleysoftMASCOM", "Process book outline: {previousOutput}"],
    "17": ["GeminiAPI", "Refine the 16-chapter book outline: {previousOutput}"],
    "18": ["MobleysoftMASCOM", "Process refined book outline: {previousOutput}"],
    "19": ["GeminiAPI", "Identify and explore the central themes and messages: {previousOutput}"],
    "20": ["MobleysoftMASCOM", "Process themes and messages: {previousOutput}"],
    "21": ["GeminiAPI", "Introduce compelling conflicts and challenges: {previousOutput}"],
    "22": ["MobleysoftMASCOM", "Process conflicts and challenges: {previousOutput}"],
    "23": ["GeminiAPI", "Strategically plan the pacing of the story: {previousOutput}"],
    "24": ["MobleysoftMASCOM", "Process story pacing: {previousOutput}"],
    "25": ["GeminiAPI", "Develop detailed outlines for each of the 16 chapters: {previousOutput}"],
    "26": ["MobleysoftMASCOM", "Process chapter outlines: {previousOutput}"],
    "27": ["GeminiAPI", "Review and enhance the 16 chapter outlines: {previousOutput}"],
    "28": ["MobleysoftMASCOM", "Process enhanced chapter outlines: {previousOutput}"],
    "29": ["GeminiAPI", "Generate front matter (title page, copyright, dedication): {previousOutput}"],
    "30": ["MobleysoftMASCOM", "Add front matter to the book: {previousOutput}"],
    "31": ["ClaudeAPI", "Write captivating chapter 1: {previousOutput}"],
    "32": ["MobleysoftMASCOM", "Process chapter 1 text: {previousOutput}"],
    "33": ["ChatGPTAPI", "Generate stunning images for chapter 1: {previousOutput}"],
    "34": ["MobleysoftMASCOM", "Add chapter 1 and images to the book: {previousOutput}"],
    "35": ["ClaudeAPI", "Write captivating chapter 2: {previousOutput}"],
    "36": ["MobleysoftMASCOM", "Process chapter 2 text: {previousOutput}"],
    "37": ["ChatGPTAPI", "Generate stunning images for chapter 2: {previousOutput}"],
    "38": ["MobleysoftMASCOM", "Add chapter 2 and images to the book: {previousOutput}"],
    "39": ["ClaudeAPI", "Write captivating chapter 3: {previousOutput}"],
    "40": ["MobleysoftMASCOM", "Process chapter 3 text: {previousOutput}"],
    "41": ["ChatGPTAPI", "Generate stunning images for chapter 3: {previousOutput}"],
    "42": ["MobleysoftMASCOM", "Add chapter 3 and images to the book: {previousOutput}"]
